cd c:\Windows\system32\inetsrv
./appcmd.exe add apppool /name:"commonservice.comm100.io" /managedRuntimeVersion:v4.0 /managedPipelineMode:Integrated /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543"
./appcmd.exe add site /name:"commonservice.comm100.io"  /bindings:"http/*:80:commonservice.comm100.io,https/*:443:commonservice.comm100.io" /physicalPath:"C:\website\commonservice.comm100.io" /applicationDefaults.applicationPool:"commonservice.comm100.io" /virtualDirectoryDefaults.userName:"WebUser" /virtualDirectoryDefaults.password:"skfksAdsds!@32543"
./appcmd.exe add apppool /name:"commonservice.comm100.io.AndroidPushNotification" /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543"
./appcmd.exe add apppool /name:"commonservice.comm100.io.IphonePushService" /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543"
./appcmd.exe add apppool /name:"commonservice.comm100.io.TranslateService" /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543" 
./appcmd.exe add apppool /name:"commonservice.comm100.io.webRTCSignalingService" /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543" 
./appcmd.exe add apppool /name:"commonservice.comm100.io.ScreenSharingService" /processModel.identityType:"SpecificUser" /processModel.userName:"WebUser" /processModel.password:"skfksAdsds!@32543"

./appcmd.exe add app /site.name:"commonservice.comm100.io" /path:"/AndroidPushNotification" /physicalPath:"C:\website\commonservice.comm100.io\AndroidPushNotification" /applicationpool:"commonservice.comm100.io.AndroidPushNotification" /virtualDirectoryDefaults.userName:"WebUser"
./appcmd.exe add app /site.name:"commonservice.comm100.io" /path:"/IphonePushService" /physicalPath:"C:\website\commonservice.comm100.io\IphonePushService" /applicationpool:"commonservice.comm100.io.IphonePushService" /virtualDirectoryDefaults.userName:"WebUser" /virtualDirectoryDefaults.password:"skfksAdsds!@32543"
./appcmd.exe add app /site.name:"commonservice.comm100.io" /path:"/TranslateService" /physicalPath:"C:\website\commonservice.comm100.io\TranslateService" /applicationpool:"commonservice.comm100.io.TranslateService" /virtualDirectoryDefaults.userName:"WebUser" /virtualDirectoryDefaults.password:"skfksAdsds!@32543"
./appcmd.exe add app /site.name:"commonservice.comm100.io" /path:"/webRTCSignalingService" /physicalPath:"C:\website\commonservice.comm100.io\webRTCSignalingService" /applicationpool:"commonservice.comm100.io.webRTCSignalingService" /virtualDirectoryDefaults.userName:"WebUser" /virtualDirectoryDefaults.password:"skfksAdsds!@32543"
./appcmd.exe add app /site.name:"commonservice.comm100.io" /path:"/ScreenSharingService" /physicalPath:"C:\website\commonservice.comm100.io\ScreenSharingService" /applicationpool:"commonservice.comm100.io.ScreenSharingService" /virtualDirectoryDefaults.userName:"WebUser" /virtualDirectoryDefaults.password:"skfksAdsds!@32543"
